[package]
name = "psync"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1.88"
chrono = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
eframe = { workspace = true }
egui_extras = { workspace = true }
env_logger = { workspace = true }
futures = "0.3.31"
itertools = { workspace = true }
keyring = { version = "3.6.2", features = ["apple-native", "windows-native", "linux-native"] }
reqwest = { version = "0.12.20", features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "macros", "migrate", "chrono", "json"] }
tokio = { version = "1.45.1", features = ["full"] }
