[package]
name = "pterry"
version = "0.1.0"
edition = "2024"
rust-version = "1.92"

[dependencies]
egui = "0.34"
egui-winit = "0.34"
eframe = { version = "0.34", default-features = false, features = ["default_fonts", "glow"] } # specify glow explicitly
rquickjs = { version = "0.6", features = ["full", "macro", "parallel"] }
window-vibrancy = "0.5"
crossbeam-channel = "0.5"
tokio = { version = "1.0", features = ["full"] }
notify = "6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
tempfile = "3.8"
objc = { version = "0.2.7", optional = true }
async-trait = "0.1"
oxc = { version = "0.114", features = ["transformer", "codegen", "semantic"] }
arboard = "3.3"
chrono = { version = "0.4", features = ["serde"] }
ureq = { version = "2", features = ["tls"] }
global-hotkey = "0.7"
rolldown = "0.1"
flate2 = "1"
tar = "0.4"
oxc_resolver = "=11.10.0"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp"] }
base64 = "0.22"
sha2 = "0.10"
sha1 = "0.10"
md5 = "0.7"

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = { version = "0.13", features = ["allow-unsafe-code"] }

[features]
default = []
macos = ["objc"]
