[package]
name = "pstore"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
keyring = { version = "3.6.2", features = ["apple-native", "windows-native", "linux-native"] }
serde = { workspace = true }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "macros", "migrate", "chrono", "json"] }
tokio = { workspace = true }

