[package]
name = "ptime"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.10.5"
nom = "7.1.1"
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.2.4", features = ["derive"]}
serde = { version = "1.0.163", features = ["derive"] }

tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
pstore = { path = "../pstore" }
anyhow = { workspace = true }
[dev-dependencies]
tempfile = "3"
temp-env = "0.3.4"
